version: '3'

services:
  library-info-app:
    build: .
    container_name: library-info-app
    ports:
    - 8080:8080
    links:
    - db
  db:
    image: mongo:latest
    container_name: mongocontainer
    ports:
    - 27017:27017
