server:
  port: 8101

spring:
  data:
    mongodb:
      host: ${MONGO_HOST}
      database: ${DB_NAME}
      port: ${MONGO_PORT}
  kafka:
    consumer:
      group-id: ${KAFKA_GROUP}
      auto-offset-reset: earliest
    bootstrap-servers: ${KAFKA_ENDPOINT}


---
spring:
  profiles: local
  data:
    mongodb:
      host: localhost
      database: call-service-test
      port: 27017
  kafka:
    consumer:
      group-id: call-task-service
    bootstrap-servers: localhost:9092

---
spring:
  profiles: no-kafka
  data:
    mongodb:
      host: localhost
      database: call-service-test
      port: 27017
