server:
  port: 8080

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
  datasource:
    name: H2-DS
    url: jdbc:h2:mem:library_db
    data-username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  data:
    mongodb:
      host: localhost
      port: 27017
      database: spring-boot-migration-app-db

management:
  endpoints:
    web:
      exposure:
        include: threaddump, env, configprops
