version: '3'

services:
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=call-task-service
    ports:
      - 27017:27017
    expose:
      - 27017/tcp
    networks:
      internal:
        aliases:
          - mongo
  call-task-service:
    networks:
      internal:
        aliases:
          - call-task-service
    ports:
      - 8081:8081
    expose:
      - 8081/tcp
    environment:
      - LOG_LEVEL_ROOT=${LOG_LEVEL_ROOT:-INFO}
      - LOG_LEVEL_APP=${LOG_LEVEL_APP:-INFO}
      - MONGO_HOST=mongo
      - DB_NAME=call-task-service
      - PORT=27017
      - KAFKA_GROUP=call-task-service
      - KAFKA_ENDPOINT=localhost:9092
    build: '.'
networks:
  internal:
    driver: bridge

