server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include:
          - beans
          - health
          - metrics
          - env
          - configprops
          - mappings
          - logfile

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: spring-boot-app-db
