server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: threaddump, env, configprops

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: spring-boot-app-db
