server:
  port: 3500

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    web:
      server:
        auto-time-requests: true
  health:
    diskspace:
      enabled: true
    mongo:
      enabled: true
    db:
      enabled: true
    defaults:
      enabled: true
  endpoint:
    health:
      show-details: always

logging:
  file: "library-info-app.log"

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: spring-boot-app-db
