server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    web:
      server:
        auto-time-requests: true
  health:
    diskspace:
      enabled: true
    mongo:
      enabled: true
    db:
      enabled: true
    defaults:
      enabled: true
  endpoint:
    health:
      show-details: always

logging:
  file: "library-info-app.log"

---
spring:
  profiles: docker
  data:
    mongodb:
      uri: mongodb://mongocontainer:27017/spring-boot-app-db

---
spring:
  profiles: local
  data:
    mongodb:
      host: localhost
      port: 27017
