
DROP TABLE IF EXISTS AUTHORS;
DROP TABLE IF EXISTS BOOKS;
DROP TABLE IF EXISTS GENRES;
DROP TABLE IF EXISTS BOOKS_AUTHORS;
DROP TABLE IF EXISTS BOOKS_GENRES;


CREATE TABLE IF NOT EXISTS AUTHORS
(
  ID BIGINT not null primary key,
  NAME VARCHAR not null
);

CREATE TABLE IF NOT EXISTS BOOKS
(
  ID BIGINT not null primary key,
  TITLE VARCHAR not null
);

CREATE TABLE IF NOT EXISTS GENRES
(
  ID BIGINT not null primary key,
  NAME VARCHAR not null constraint GENRES_NAME_UINDEX unique
);

CREATE TABLE IF NOT EXISTS BOOKS_AUTHORS
(
  BOOK_ID   BIGINT not null,
  AUTHOR_ID BIGINT not null,
  constraint BOOKS_AUTHORS_BOOK_ID_AUTHOR_ID_PK
  primary key (BOOK_ID, AUTHOR_ID),
  constraint BOOKS_AUTHORS_BOOKS_ID_FK
  foreign key (BOOK_ID) references BOOKS,
  constraint BOOKS_AUTHORS_AUTHORS_ID_FK
  foreign key (AUTHOR_ID) references AUTHORS
);

CREATE TABLE IF NOT EXISTS BOOKS_GENRES
(
  BOOK_ID  BIGINT not null,
  GENRE_ID BIGINT not null,
  constraint BOOKS_GENRES_BOOK_ID_GENRE_ID_PK
  primary key (BOOK_ID, GENRE_ID),
  constraint BOOKS_GENRES_BOOKS_ID_FK
  foreign key (BOOK_ID) references BOOKS,
  constraint BOOKS_GENRES_GENRES_ID_FK
  foreign key (GENRE_ID) references GENRES
);


SET REFERENTIAL_INTEGRITY FALSE;

TRUNCATE TABLE AUTHORS;
TRUNCATE TABLE GENRES;
TRUNCATE TABLE BOOKS;
TRUNCATE TABLE BOOKS_AUTHORS;
TRUNCATE TABLE BOOKS_GENRES;

SET REFERENTIAL_INTEGRITY TRUE;
